In [2]:
import torch
import numpy as np

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data), print(data)

tensor([[1, 2],
        [3, 4]])
[[1, 2], [3, 4]]


(None, None)

In [5]:
a = [1, 2,3.]
type(a)

list

In [6]:
b = torch.tensor(a)
print(b),print(type(b))

tensor([1., 2., 3.])
<class 'torch.Tensor'>


(None, None)

In [7]:
b.dtype

torch.float32

In [8]:
a = np.random.random((2, 3))
print(a)


[[0.11324495 0.8444431  0.85550044]
 [0.07863155 0.29674935 0.03315097]]


In [11]:
b = torch.tensor(a) # 默认的数据类型是float32
b

tensor([[0.1132, 0.8444, 0.8555],
        [0.0786, 0.2967, 0.0332]], dtype=torch.float64)

In [12]:
c = torch.ones_like(b)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
c = torch.rand_like(b)
c # 形状和b是一样的

tensor([[0.3233, 0.2933, 0.2590],
        [0.5202, 0.6896, 0.6097]], dtype=torch.float64)

In [17]:
a = torch.rand((2, 2))
a,a.dtype,a.shape,a.device

(tensor([[0.8862, 0.5151],
         [0.3957, 0.5932]]),
 torch.float32,
 torch.Size([2, 2]),
 device(type='cpu'))

In [18]:
'''关于tensor的操作'''

'关于tensor的操作'

In [19]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = a.to("cuda")

In [25]:
x=torch.tensor([1,2,3])
torch.is_tensor(x)

True

In [26]:
a = torch.tensor(1)
a

tensor(1)

In [28]:
torch.is_nonzero(a)

True

In [32]:
a = torch.randn(4, 5)
a,torch.numel(a) # 元素的总个数

(tensor([[ 0.8976, -1.3612, -0.4346, -1.4343, -0.4002],
         [ 2.3532, -1.1779,  0.8074,  0.3935, -1.2263],
         [ 1.2639,  0.9777, -1.8622, -1.3100,  1.0453],
         [ 0.6596,  1.1827,  2.0541,  1.2547,  0.6039]]),
 20)

In [36]:
a = torch.zeros([5, 5])
a

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [37]:
a = torch.arange(5)
a

tensor([0, 1, 2, 3, 4])

In [38]:
torch.arange(0, 5, 2)

tensor([0, 2, 4])

In [40]:
a = torch.range(0, 5)
a

C:\Users\lzf\AppData\Local\Temp/ipykernel_18808/1341453779.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a = torch.range(0, 5)


tensor([0., 1., 2., 3., 4., 5.])

In [41]:
for i in torch.arange(10):
    print('epoch:', i)

epoch: tensor(0)
epoch: tensor(1)
epoch: tensor(2)
epoch: tensor(3)
epoch: tensor(4)
epoch: tensor(5)
epoch: tensor(6)
epoch: tensor(7)
epoch: tensor(8)
epoch: tensor(9)


In [44]:
torch.full((2,3), 1.2)

tensor([[1.2000, 1.2000, 1.2000],
        [1.2000, 1.2000, 1.2000]])

In [45]:
x = torch.randn(2, 3)
x

tensor([[-1.1380, -1.2085, -0.6266],
        [-0.5262,  1.9976,  1.0424]])

In [46]:
torch.cat((x, x, x), 0) # 行连接

tensor([[-1.1380, -1.2085, -0.6266],
        [-0.5262,  1.9976,  1.0424],
        [-1.1380, -1.2085, -0.6266],
        [-0.5262,  1.9976,  1.0424],
        [-1.1380, -1.2085, -0.6266],
        [-0.5262,  1.9976,  1.0424]])

In [47]:
torch.cat((x, x, x), 1) # 列连接

tensor([[-1.1380, -1.2085, -0.6266, -1.1380, -1.2085, -0.6266, -1.1380, -1.2085,
         -0.6266],
        [-0.5262,  1.9976,  1.0424, -0.5262,  1.9976,  1.0424, -0.5262,  1.9976,
          1.0424]])