In [1]:
import torch
import numpy as np

In [2]:
torch.arange(11).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10]))

In [3]:
b = torch.rand(2, 3)
b

tensor([[0.1810, 0.5939, 0.8818],
        [0.8143, 0.3020, 0.0869]])

In [24]:
torch.chunk(b, chunks = 2, dim = 0)

(tensor([[0, 1]]), tensor([[2, 3]]))

In [7]:
t = torch.tensor([[1, 2], [3, 4]])
t

tensor([[1, 2],
        [3, 4]])

In [8]:
torch.gather(t, 1, torch.tensor([[0,0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [9]:
a = torch.arange(4.)
a

tensor([0., 1., 2., 3.])

In [10]:
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [11]:
b = torch.tensor([[0, 1], [2, 3]])
b

tensor([[0, 1],
        [2, 3]])

In [12]:
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

In [15]:
src = torch.arange(1, 11).reshape((2, 5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [16]:
index = torch.tensor([[0, 1, 2, 0]])
index

tensor([[0, 1, 2, 0]])

In [17]:
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src) # https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html#torch.Tensor.scatter_

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [18]:
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [22]:
torch.split(a, 2, 0)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [23]:
torch.split(a, [1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

In [26]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [27]:
y = torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [28]:
b = torch.rand(3, 2)
b

tensor([[0.6610, 0.2613],
        [0.3979, 0.2880],
        [0.6506, 0.5000]])

In [29]:
a = torch.rand(3, 2)
a

tensor([[0.1834, 0.2441],
        [0.7729, 0.9603],
        [0.2638, 0.5119]])

In [35]:
torch.stack((a, b), dim = 0).shape

torch.Size([2, 3, 2])

In [37]:
torch.stack((a, b), dim = 1).shape

torch.Size([3, 2, 2])

In [39]:
src = torch.tensor([[4, 3, 5],[6, 7, 8]])
src

tensor([[4, 3, 5],
        [6, 7, 8]])

In [40]:
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

In [42]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [43]:
x.tile((2,)) # copy几次

tensor([1, 2, 3, 1, 2, 3])

In [44]:
y = torch.tensor([[1, 2], [3, 4]])
y

tensor([[1, 2],
        [3, 4]])

In [45]:
torch.tile(y, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

In [49]:
x = torch.randn(2, 3)
x,x.shape

(tensor([[-0.1894, -0.3572,  0.2505],
         [ 0.4268,  1.1769,  1.1961]]),
 torch.Size([2, 3]))

In [50]:
b = torch.transpose(x, 0, 1)
b,b.shape

(tensor([[-0.1894,  0.4268],
         [-0.3572,  1.1769],
         [ 0.2505,  1.1961]]),
 torch.Size([3, 2]))

In [51]:
torch.unbind(torch.tensor([[1, 2, 3],[4, 5, 6],[7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [52]:
x = torch.tensor([1, 2, 3, 4])
x 

tensor([1, 2, 3, 4])

In [53]:
torch.unsqueeze(x, 0)# 扩充维度

tensor([[1, 2, 3, 4]])

In [54]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

In [55]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x,y

(tensor([[-0.9124, -2.7596],
         [ 0.5900, -0.1682],
         [ 1.3131, -0.2238]]),
 tensor([[1., 1.],
         [1., 1.],
         [1., 1.]]))

In [56]:
torch.where(x > 0, x, y)

tensor([[1.0000, 1.0000],
        [0.5900, 1.0000],
        [1.3131, 1.0000]])

In [57]:
x = torch.randn(2, 2, dtype=torch.double)
x

tensor([[ 0.9243,  0.8271],
        [-0.1070, -1.4021]], dtype=torch.float64)

In [58]:
torch.where(x > 0, x, 0.)

tensor([[0.9243, 0.8271],
        [0.0000, 0.0000]], dtype=torch.float64)

In [59]:
torch.randint(3, 5, (3,))

tensor([3, 4, 4])

In [60]:
torch.randint(10, (2, 2))

tensor([[6, 6],
        [3, 5]])

In [61]:
torch.randperm(4)

tensor([3, 2, 1, 0])

In [62]:
torch.randperm(10)

tensor([9, 5, 6, 0, 4, 1, 8, 7, 3, 2])