In [1]:
import torch
from torch import nn

In [2]:
torch.__version__

'1.9.1+cpu'

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using {device} device")

Using cpu device


In [8]:
input_inage = torch.rand(3, 28,28)
print(input_inage.size())

torch.Size([3, 28, 28])


In [9]:
flatten = nn.Flatten()
flatten

Flatten(start_dim=1, end_dim=-1)

In [10]:
flat_images = flatten(input_inage)
print(flat_images.size())

torch.Size([3, 784])


In [12]:
flat_images

tensor([[0.6336, 0.0933, 0.3128,  ..., 0.0794, 0.5117, 0.2342],
        [0.1209, 0.6263, 0.6245,  ..., 0.5181, 0.4648, 0.0137],
        [0.4101, 0.3314, 0.7162,  ..., 0.6634, 0.5784, 0.8486]])

In [23]:
layer1 = nn.Linear(in_features = 28 *28, out_features = 20)
hidden1 = layer1(flat_images)
print(hidden1.size())

torch.Size([3, 20])


In [24]:
hidden1

tensor([[-0.1927, -0.1566, -0.9026, -0.1495,  0.4793,  0.1761, -0.5902, -0.2361,
          0.4247, -0.0660, -0.5540,  0.3544, -0.2516, -0.2190,  0.2476,  0.0837,
          0.5029, -0.0915,  0.4970, -0.0328],
        [-0.3627,  0.0556, -1.2361, -0.1456,  0.4217, -0.3097, -0.5516,  0.0967,
          0.1601, -0.3682, -0.4937,  0.6475,  0.0986,  0.0873,  0.3366,  0.0552,
         -0.0048, -0.1957,  0.2750, -0.0193],
        [-0.6981, -0.2631, -0.5183, -0.2163,  0.0453, -0.3200, -0.2077,  0.1095,
          0.5336,  0.0414, -0.2220,  0.2178,  0.0239, -0.1892,  0.0593,  0.4243,
          0.6102, -0.5684,  0.0471,  0.4159]], grad_fn=<AddmmBackward>)

In [25]:
hidden1 = nn.ReLU()(hidden1)
hidden1

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.4793, 0.1761, 0.0000, 0.0000, 0.4247,
         0.0000, 0.0000, 0.3544, 0.0000, 0.0000, 0.2476, 0.0837, 0.5029, 0.0000,
         0.4970, 0.0000],
        [0.0000, 0.0556, 0.0000, 0.0000, 0.4217, 0.0000, 0.0000, 0.0967, 0.1601,
         0.0000, 0.0000, 0.6475, 0.0986, 0.0873, 0.3366, 0.0552, 0.0000, 0.0000,
         0.2750, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0453, 0.0000, 0.0000, 0.1095, 0.5336,
         0.0414, 0.0000, 0.2178, 0.0239, 0.0000, 0.0593, 0.4243, 0.6102, 0.0000,
         0.0471, 0.4159]], grad_fn=<ReluBackward0>)

In [26]:
hidden1.size()

torch.Size([3, 20])

In [28]:
seq_models = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)

In [29]:
seq_models

Sequential(
  (0): Flatten(start_dim=1, end_dim=-1)
  (1): Linear(in_features=784, out_features=20, bias=True)
  (2): ReLU()
  (3): Linear(in_features=20, out_features=10, bias=True)
)

In [30]:
input_image = torch.rand(3, 28, 28)
logits = seq_models(input_image)
logits

tensor([[ 0.0185, -0.0632, -0.1073,  0.2588,  0.2447, -0.0520, -0.1022,  0.2497,
         -0.2631,  0.2393],
        [ 0.0666, -0.0804, -0.1754,  0.2452,  0.2329, -0.0418, -0.0703,  0.2197,
         -0.2219,  0.2779],
        [ 0.0570,  0.0043, -0.1424,  0.2186,  0.1989, -0.2052, -0.0805,  0.1630,
         -0.1475,  0.2087]], grad_fn=<AddmmBackward>)

In [31]:
softmax = nn.Softmax(dim = 1)
softmax

Softmax(dim=1)

In [32]:
pred_probab = softmax(logits)
pred_probab

tensor([[0.0961, 0.0885, 0.0847, 0.1222, 0.1205, 0.0895, 0.0851, 0.1211, 0.0725,
         0.1198],
        [0.1006, 0.0868, 0.0789, 0.1202, 0.1188, 0.0902, 0.0877, 0.1172, 0.0754,
         0.1242],
        [0.1018, 0.0965, 0.0834, 0.1196, 0.1173, 0.0783, 0.0887, 0.1131, 0.0829,
         0.1184]], grad_fn=<SoftmaxBackward>)

In [34]:
pred_probab.size()

torch.Size([3, 10])