#### 1.张量的数据类型

In [1]:
import numpy as np
import torch

In [2]:
i = torch.tensor(1) # 默认为int64
print(i, i.dtype)

tensor(1) torch.int64


In [4]:
x = torch.tensor(2.0) # 默认为float32
print(x, x.dtype)

tensor(2.) torch.float32


In [5]:
b = torch.tensor(True)
print(b, b.dtype)

tensor(True) torch.bool


In [6]:
i = torch.tensor(1, dtype = torch.int32) # 指定数据类型
print(i, i.dtype)

tensor(1, dtype=torch.int32) torch.int32


In [8]:
b = torch.tensor(2.0, dtype = torch.double)
print(b, b.dtype)

tensor(2., dtype=torch.float64) torch.float64


In [16]:
# 使用指定类型构造函数
# 但是随机构造的却是int32
i = torch.IntTensor(5)
print(i, i.dtype)

tensor([0, 0, 0, 0, 0], dtype=torch.int32) torch.int32


In [17]:
x = torch.tensor(np.array(2.0))
print(x, x.dtype)

tensor(2., dtype=torch.float64) torch.float64


In [18]:
np.array([1, 0, 2, 0])

array([1, 0, 2, 0])

In [19]:
b = torch.BoolTensor(np.array([1, 0, 2, 0]))
print(b, b.type)

tensor([ True, False,  True, False]) <built-in method type of Tensor object at 0x000001CA65C045E0>


In [22]:
# 不同类型进行转换
i = torch.tensor(1)
print(i, i.dtype)

tensor(1) torch.int64


In [23]:
x = i.float(); print(x, x.dtype)

y = i.type(torch.float); print(y, y.dtype)

z = i.type_as(x); print(z, z.dtype)

tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


#### 2. 张量的维度

In [24]:
import numpy as np
import torch

#### 标量是0维，向量是1维，矩阵是2维，有几层中括号，就是多少维张量

In [25]:
scalar = torch.tensor(True)
scalar

tensor(True)

In [26]:
scalar.dim()

0

In [27]:
v = torch.tensor([2.0, 3.0, 1.0])
print(v, v.dim())

tensor([2., 3., 1.]) 1


In [28]:
m = torch.tensor([[1, 2], [3, 4]])
print(m, m.dim())

tensor([[1, 2],
        [3, 4]]) 2


In [31]:
t3 = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(t3, t3.dim())

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]) 3


In [30]:
t4 = torch.tensor([[[[1, 2], [3, 4], [5, 6]]]])
print(t4, t4.dim())

tensor([[[[1, 2],
          [3, 4],
          [5, 6]]]]) 4


#### 3. 张量的尺度

In [1]:
import numpy as np
import torch

In [3]:
s = torch.tensor(True)
print(s,s.size())

tensor(True) torch.Size([])


In [4]:
v = torch.tensor([1, 2, 3, 4])
print(v, v.shape, v.size())

tensor([1, 2, 3, 4]) torch.Size([4]) torch.Size([4])


In [5]:
# 使用view可以改变尺寸
v = torch.tensor(range(12))
v

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
print(v.size(), v.shape)

torch.Size([12]) torch.Size([12])


In [7]:
matrix34 = v.view(3, 4) # 3行4列
print(matrix34, matrix34.size())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4])


In [8]:
matrix43 = v.view(4, -1) # 4行3列，-1表示该位置长度是由程序自动推断出来的
print(matrix43, matrix43.shape)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]) torch.Size([4, 3])


In [9]:
# 有些操作会让张量存储结构扭曲，直接使用view会失败，可以使用reshape方法

In [10]:
matrix26 = torch.arange(0, 12).view(2, -1)
matrix26

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [11]:
# 转置操作会让张量存储结构扭曲
matrix62 = matrix26.t()
matrix62

tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])

In [12]:
matrix62.is_contiguous() # 判断tensor是否连续

False

In [15]:
#matrix34 = matrix62.view(3, 4) 不能用，会出错
matrix34 = matrix62.reshape(3, -1)
matrix34

tensor([[ 0,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])

#### 4. 张量和Numpy数组

In [16]:
import numpy as np
import torch

In [22]:
# 先建立numpy，然后使用from_numpy建立tensor
arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print('先建立numpy，然后将numpy类型转变为tensor')
print(arr)
print(tensor)

先建立numpy，然后将numpy类型转变为tensor
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)


In [23]:
print('给arr增加1，观看两者的变化')
np.add(arr, 1, out = arr)
print(arr)
print(tensor) # 可以看到给arr增加1，tensor中的内容也是变化的，说明使用from_numpy，arr和tensor是共享数据内存的

给arr增加1，观看两者的变化
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


In [24]:
tensor = torch.zeros(3)
arr = tensor.numpy()
print('从建立好的tensor中转变为numpy类型')
print('tensor:', tensor)
print('numpy:', arr)

从建立好的tensor中转变为numpy类型
tensor: tensor([0., 0., 0.])
numpy: [0. 0. 0.]


In [26]:
print('给tensor增加1，然后再返回tensor，下划线代表将结果返回原来的变量')
tensor.add_(1)
print('tensor:', tensor)
print('numpy:', arr) # 使用add_1也是共享数据内存的

给tensor增加1，然后再返回tensor，下划线代表将结果返回原来的变量
tensor: tensor([1., 1., 1.])
numpy: [1. 1. 1.]


In [28]:
# 可以使用clone()方法中段这种联系
tensor = torch.zeros(3)
arr = tensor.clone().numpy() # 也可以使用     arr = tensor.data.numpy()
print('先建立tensor，然后转变为numpy类型')
print('tensor:', tensor)
print('numpy:', arr)

先建立tensor，然后转变为numpy类型
tensor: tensor([0., 0., 0.])
numpy: [0. 0. 0.]


In [29]:
print('tensor自身加1，利用clone()或者data可以中断联系')
tensor.add_(1)
print('tensor:', tensor)
print('arr:', arr)

tensor自身加1，利用clone()或者data可以中断联系
tensor: tensor([1., 1., 1.])
arr: [0. 0. 0.]


In [33]:
s = torch.tensor(1.0)
print('tensor and type:\n', s, s.dtype)
#print('\n')
print('使用item()方法可以将tensor转变为Python的数值:')
s_item = s.item()
print('s_item and type:', s_item, type(s_item))

tensor and type:
 tensor(1.) torch.float32
使用item()方法可以将tensor转变为Python的数值:
s_item and type: 1.0 <class 'float'>


In [35]:
t = torch.rand(2, 2)
print('tensor and type:\n', t, type(t))
print('使用tolist()方法可以将tensor转变为Python的数值列表')
t_list = t.tolist()
print('t_list and type:\n', t_list, type(t_list))

tensor and type:
 tensor([[0.8489, 0.6734],
        [0.2944, 0.1720]]) <class 'torch.Tensor'>
使用tolist()方法可以将tensor转变为Python的数值列表
t_list and type:
 [[0.8489311933517456, 0.6734045743942261], [0.2943814992904663, 0.17199105024337769]] <class 'list'>
