In [1]:
print('张量的操作包括:结构操作和数学运算')
print('结构操作包括：创建,索引切片,维度变换,合并分割')
print('数学运算包括: 标量运算,向量运算,矩阵运算')

张量的操作包括:结构操作和数学运算
结构操作包括：创建,索引切片,维度变换,合并分割
数学运算包括: 标量运算,向量运算,矩阵运算


### 1. 创建张量

In [3]:
print('张量的创建的许多方法和numpy中的创建array的方法很像')

张量的创建的许多方法和numpy中的创建array的方法很像


In [4]:
import numpy as np
import torch

In [5]:
a = torch.tensor([1, 2, 3], dtype = torch.float)
print(a, type(a), a.shape)

tensor([1., 2., 3.]) <class 'torch.Tensor'> torch.Size([3])


In [7]:
b = torch.arange(1, 10, step = 2)
print(b)
print(b.data)

tensor([1, 3, 5, 7, 9])
tensor([1, 3, 5, 7, 9])


In [8]:
c = torch.linspace(0.0, 2 * 3.14, 10) # 每次加的是相同的数，范围是[a,b]
print(c)

tensor([0.0000, 0.6978, 1.3956, 2.0933, 2.7911, 3.4889, 4.1867, 4.8844, 5.5822,
        6.2800])


In [9]:
d = torch.zeros((3, 3))
d

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
a = torch.ones((3, 3), dtype = torch.int)
print(a, a.dtype)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32) torch.int32


In [13]:
b = torch.zeros_like(a, dtype = torch.float)
print(b, b.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) torch.float32


In [15]:
torch.fill_(b, 5)
print(b)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])


In [16]:
torch.rand([5])

tensor([0.9876, 0.6890, 0.9795, 0.0151, 0.0380])

In [18]:
print('均匀随机分布')
torch.manual_seed(0)
min, max = 0, 10
a = min + (max - min) * torch.rand([5])
print('均匀随机分布值为:\n', a)

均匀随机分布
均匀随机分布值为:
 tensor([4.9626, 7.6822, 0.8848, 1.3203, 3.0742])


In [19]:
print('正太分布随机')
b = torch.normal(mean = torch.zeros(3, 3), std = torch.ones(3, 3))
b

正太分布随机


tensor([[ 0.5507,  0.2704,  0.6472],
        [ 0.2490, -0.3354,  0.4564],
        [-0.6255,  0.4539, -1.3740]])

In [21]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [22]:
torch.randn((3, 3))

tensor([[ 2.8474, -0.7322,  0.3833],
        [ 1.1000, -0.0877,  0.4154],
        [ 0.6426, -2.1881,  0.8920]])

In [23]:
print('正太分布随机')
mean, std = 2, 5
c = std * torch.randn(3, 3) + mean
c

正太分布随机


tensor([[ 5.7277,  0.7698,  6.2558],
        [ 0.2491, 10.4405, -8.7873],
        [-4.9637,  0.1947, 11.3698]])

In [27]:
print('整数随机排列, 从0到19中,20个数随机打乱')
d = torch.randperm(20)
d

整数随机排列, 从0到19中,20个数随机打乱


tensor([ 7,  2, 17,  6,  1, 12, 13,  3,  9, 11,  0, 18,  5,  4, 15,  8, 16, 14,
        10, 19])

In [28]:
print('单位矩阵')
i = torch.eye(3, 3) # 单位矩阵
i

单位矩阵


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [29]:
print('对角矩阵')
t = torch.diag(torch.tensor([1, 2, 3]))
t

对角矩阵


tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

### 2. 索引切片

In [31]:
print('张量的索引切片方式和numpy几乎是一样的.切片时支持省略参数和省略号')
print('可以通过索引和切片对部分元素进行修改')

张量的索引切片方式和numpy几乎是一样的.切片时支持省略参数和省略号
可以通过索引和切片对部分元素进行修改


In [34]:
print('均匀随机分布')
# torch.floor()方法返回一个新的张量
torch.manual_seed(0)
min, max = 0, 10
t = torch.floor(min + (max - min) * torch.randn([5, 5])).int()
t

均匀随机分布


tensor([[-12, -12,  -3,  -5,   8],
        [  6,  -4, -22,   3,  -2],
        [ 14,   2,   1,   8,  -2],
        [ -2,  -7,  12,  20,   0],
        [  6,  -5,  -9, -24,  -2]], dtype=torch.int32)

In [35]:
print('第0行的元素为:{}'.format(t[0]))

第0行的元素为:tensor([-12, -12,  -3,  -5,   8], dtype=torch.int32)


In [37]:
print('倒数第1行的元素为:{}'.format(t[-1]))

倒数第1行的元素为:tensor([  6,  -5,  -9, -24,  -2], dtype=torch.int32)


In [39]:
print('第一种写法:第1行第3列的值为:{}'.format(t[1, 3]))
print('第二种写法:第1行第3列的值为:{}'.format(t[1][3]))

第一种写法:第1行第3列的值为:3
第二种写法:第1行第3列的值为:3


In [41]:
print('第1行到第3行的值为:\n{}'.format(t[1:4, :]))

第1行到第3行的值为:
tensor([[  6,  -4, -22,   3,  -2],
        [ 14,   2,   1,   8,  -2],
        [ -2,  -7,  12,  20,   0]], dtype=torch.int32)


In [42]:
print('第1行到最后一行,第0列到最后一列每隔2列取一列:\n{}'.format(t[:, ::2]))

第1行到最后一行,第0列到最后一列每隔2列取一列:
tensor([[-12,  -3,   8],
        [  6, -22,  -2],
        [ 14,   1,  -2],
        [ -2,  12,   0],
        [  6,  -9,  -2]], dtype=torch.int32)


In [43]:
print('可以使用索引和切片修改部分元素:')
x = torch.tensor([[1, 2], [3, 4]], dtype = torch.float32, requires_grad = True)
x

可以使用索引和切片修改部分元素:


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [44]:
x.data[1, :] = torch.tensor([0.0, 0.0])
x

tensor([[1., 2.],
        [0., 0.]], requires_grad=True)

In [45]:
a = torch.arange(27).reshape(3, 3, 3)
a

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])

In [46]:
print('省略号可以表示多个冒号')
print(a[..., 1])

省略号可以表示多个冒号
tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]])


In [47]:
print('以上的切片方式都是相对规则的')
print('对于不规则的切片提取可以使用torch.index_selct, torch.take, torch.gather, torch.masked_select')

以上的切片方式都是相对规则的
对于不规则的切片提取可以使用torch.index_selct, torch.take, torch.gather, torch.masked_select


In [48]:
print('考试的成绩册,有4个班级,每个班级10个学生,每个学生有7门科目成绩,可以使用一个4 * 10 * 7的张量来表示')

考试的成绩册,有4个班级,每个班级10个学生,每个学生有7门科目成绩,可以使用一个4 * 10 * 7的张量来表示


In [49]:
min = 0
max = 100
scores = torch.floor(min + (max - min) * torch.rand([4, 10, 7])).int()
scores

tensor([[[24, 58,  3, 13, 24, 81, 79],
         [27, 48, 81, 99, 69, 56, 83],
         [20, 59, 11, 15, 24, 72, 70],
         [20, 65, 77, 43, 51, 61, 81],
         [98, 11, 31, 69, 91, 93, 94],
         [59,  6, 54, 18,  3, 94, 88],
         [ 0, 59, 41, 41, 27, 69, 20],
         [68, 75, 85, 68,  0, 17, 74],
         [60, 10, 21, 97, 83, 28, 37],
         [ 2, 49, 12, 11, 47, 57, 29]],

        [[79, 19, 95, 84,  7, 37, 52],
         [57, 61, 69, 52, 25, 73,  2],
         [20, 37, 25, 32,  9, 39, 60],
         [17, 47, 85, 44, 51, 45, 60],
         [81, 97, 81, 97, 46,  5, 26],
         [84, 49, 25, 11,  3,  7, 39],
         [77, 77,  1, 81, 10, 39, 29],
         [40, 40,  5,  6, 42, 50, 27],
         [68,  4, 46, 93, 29, 95, 68],
         [ 4, 81, 44, 27, 89,  9, 55]],

        [[39, 85, 63, 74, 67, 37, 39],
         [ 8, 77, 89, 84, 14, 52, 14],
         [22, 20, 67, 20, 48, 52, 82],
         [12, 15, 20, 84, 32, 92, 68],
         [56, 49, 40, 56, 38, 49, 56],
         [10, 23, 90,

In [50]:
print('抽取每个班级的第0个学生,第5个学生,第9个学生的全部成绩')
torch.index_select(scores, dim = 1, index = torch.tensor([0, 5, 9]))

抽取每个班级的第0个学生,第5个学生,第9个学生的全部成绩


tensor([[[24, 58,  3, 13, 24, 81, 79],
         [59,  6, 54, 18,  3, 94, 88],
         [ 2, 49, 12, 11, 47, 57, 29]],

        [[79, 19, 95, 84,  7, 37, 52],
         [84, 49, 25, 11,  3,  7, 39],
         [ 4, 81, 44, 27, 89,  9, 55]],

        [[39, 85, 63, 74, 67, 37, 39],
         [10, 23, 90,  9, 46, 99, 68],
         [75,  1, 86,  8, 50, 41, 23]],

        [[56, 91, 35, 20, 31,  0, 72],
         [33, 64, 38, 47, 19, 66, 65],
         [68, 83, 23, 50, 70, 53, 54]]], dtype=torch.int32)

In [54]:
print('抽取每个班级第0个学生,第5个学生,第9个学生的第1门课程,第3门课程,第6门课程成绩')
q = torch.index_select(torch.index_select(scores, dim = 1, index = torch.tensor([0, 5, 9])), dim = 2, index = torch.tensor([1, 3, 6]))
q

抽取每个班级第0个学生,第5个学生,第9个学生的第1门课程,第3门课程,第6门课程成绩


tensor([[[58, 13, 79],
         [ 6, 18, 88],
         [49, 11, 29]],

        [[19, 84, 52],
         [49, 11, 39],
         [81, 27, 55]],

        [[85, 74, 39],
         [23,  9, 68],
         [ 1,  8, 23]],

        [[91, 20, 72],
         [64, 47, 65],
         [83, 50, 54]]], dtype=torch.int32)

In [57]:
print('抽取第0个班级第0个学生的第0门课程, 第2个班级的第4个学生的第1门课程,第3个班级的第9个学生的第6门课程成绩')
# s = torch.take(scores, torch.tensor([0 * 10 * 7 + 0, 2 * 10 * 7 + 4 * 7 + 1 + 3 * 10 * 7 + 9 * 7 + 6]))
# s
#take将输入看成一维数组，输出和index同形状
s = torch.take(scores,torch.tensor([0*10*7+0,2*10*7+4*7+1,3*10*7+9*7+6]))
s

抽取第0个班级第0个学生的第0门课程, 第2个班级的第4个学生的第1门课程,第3个班级的第9个学生的第6门课程成绩


tensor([24, 49, 54], dtype=torch.int32)

In [58]:
print('抽取分数大于等于80分的分数(布尔索引)')
print('结果是1维张量')

抽取分数大于等于80分的分数(布尔索引)
结果是1维张量


In [59]:
g = torch.masked_select(scores, scores > 80)
g

tensor([81, 81, 99, 83, 81, 98, 91, 93, 94, 94, 88, 85, 97, 83, 95, 84, 85, 81,
        97, 81, 97, 84, 81, 93, 95, 81, 89, 85, 89, 84, 82, 84, 92, 90, 99, 91,
        94, 87, 86, 91, 88, 91, 93, 89, 91, 84, 83], dtype=torch.int32)

In [60]:
print('以上只能提取元素,不能修该元素,下面就进行元素的修改')

以上只能提取元素,不能修该元素,下面就进行元素的修改


In [61]:
print('torch.index_fill的选取元素的逻辑和torch.index_select相同')
print('torch.masked_fill的选取元素的逻辑和torch.mask_select相同')

torch.index_fill的选取元素的逻辑和torch.index_select相同
torch.masked_fill的选取元素的逻辑和torch.mask_select相同


In [62]:
print('如果分数大于60分,赋值为1,否则为0')
ifpass = torch.where(scores > 60, torch.tensor(1), torch.tensor(0))
ifpass

如果分数大于60分,赋值为1,否则为0


tensor([[[0, 0, 0, 0, 0, 1, 1],
         [0, 0, 1, 1, 1, 0, 1],
         [0, 0, 0, 0, 0, 1, 1],
         [0, 1, 1, 0, 0, 1, 1],
         [1, 0, 0, 1, 1, 1, 1],
         [0, 0, 0, 0, 0, 1, 1],
         [0, 0, 0, 0, 0, 1, 0],
         [1, 1, 1, 1, 0, 0, 1],
         [0, 0, 0, 1, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0]],

        [[1, 0, 1, 1, 0, 0, 0],
         [0, 1, 1, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 0],
         [1, 1, 1, 1, 0, 0, 0],
         [1, 0, 0, 0, 0, 0, 0],
         [1, 1, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 0, 0, 1, 0, 1, 1],
         [0, 1, 0, 0, 1, 0, 0]],

        [[0, 1, 1, 1, 1, 0, 0],
         [0, 1, 1, 1, 0, 0, 0],
         [0, 0, 1, 0, 0, 0, 1],
         [0, 0, 0, 1, 0, 1, 1],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 0, 0, 1, 1],
         [0, 0, 1, 0, 0, 0, 0],
         [0, 1, 0, 1, 1, 0, 1],
         [0, 0, 1, 1, 1, 0, 0],
         [1, 0, 1, 0, 0, 0, 0]],

        [[0, 1, 0, 0, 0, 0, 1],
  

In [63]:
print('将每个班级的第0个学生,第5个学生,第9个学生的全部成绩赋值为100')
torch.index_fill(scores, dim = 1, index = torch.tensor([0, 5, 9]), value = 100)
# 等价于scores.index_fill(scores, dim = 1, index = torch.tensor([0, 5, 9]), value = 100)

将每个班级的第0个学生,第5个学生,第9个学生的全部成绩赋值为100


tensor([[[100, 100, 100, 100, 100, 100, 100],
         [ 27,  48,  81,  99,  69,  56,  83],
         [ 20,  59,  11,  15,  24,  72,  70],
         [ 20,  65,  77,  43,  51,  61,  81],
         [ 98,  11,  31,  69,  91,  93,  94],
         [100, 100, 100, 100, 100, 100, 100],
         [  0,  59,  41,  41,  27,  69,  20],
         [ 68,  75,  85,  68,   0,  17,  74],
         [ 60,  10,  21,  97,  83,  28,  37],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [ 57,  61,  69,  52,  25,  73,   2],
         [ 20,  37,  25,  32,   9,  39,  60],
         [ 17,  47,  85,  44,  51,  45,  60],
         [ 81,  97,  81,  97,  46,   5,  26],
         [100, 100, 100, 100, 100, 100, 100],
         [ 77,  77,   1,  81,  10,  39,  29],
         [ 40,  40,   5,   6,  42,  50,  27],
         [ 68,   4,  46,  93,  29,  95,  68],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [  8,  77,  89,  84, 

In [64]:
print('将分数小于60分的分数赋值成60分')
b = torch.masked_fill(scores, scores < 60, 60)
# 等价于b = scores.masked_fill(scores, scores < 60, 60)
b

将分数小于60分的分数赋值成60分


tensor([[[60, 60, 60, 60, 60, 81, 79],
         [60, 60, 81, 99, 69, 60, 83],
         [60, 60, 60, 60, 60, 72, 70],
         [60, 65, 77, 60, 60, 61, 81],
         [98, 60, 60, 69, 91, 93, 94],
         [60, 60, 60, 60, 60, 94, 88],
         [60, 60, 60, 60, 60, 69, 60],
         [68, 75, 85, 68, 60, 60, 74],
         [60, 60, 60, 97, 83, 60, 60],
         [60, 60, 60, 60, 60, 60, 60]],

        [[79, 60, 95, 84, 60, 60, 60],
         [60, 61, 69, 60, 60, 73, 60],
         [60, 60, 60, 60, 60, 60, 60],
         [60, 60, 85, 60, 60, 60, 60],
         [81, 97, 81, 97, 60, 60, 60],
         [84, 60, 60, 60, 60, 60, 60],
         [77, 77, 60, 81, 60, 60, 60],
         [60, 60, 60, 60, 60, 60, 60],
         [68, 60, 60, 93, 60, 95, 68],
         [60, 81, 60, 60, 89, 60, 60]],

        [[60, 85, 63, 74, 67, 60, 60],
         [60, 77, 89, 84, 60, 60, 60],
         [60, 60, 67, 60, 60, 60, 82],
         [60, 60, 60, 84, 60, 92, 68],
         [60, 60, 60, 60, 60, 60, 60],
         [60, 60, 90,

### 3. 维度变换

In [66]:
print('torch.reshape:改变张量的形状')
print('torch.squeeze:减少维度')
print('torch.unsqueeze:增加维度')
print('torch.transpose:交换维度')

torch.reshape:改变张量的形状
torch.squeeze:减少维度
torch.unsqueeze:增加维度
torch.transpose:交换维度


In [67]:
torch.manual_seed(0)
min, max = 0, 255
a = (min + (max - min) * torch.rand([1, 3, 3, 2])).int()
print(a.shape)
print(a)

torch.Size([1, 3, 3, 2])
tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [68]:
b = a.reshape([3, 6])
print(b.shape)
print(b)

torch.Size([3, 6])
tensor([[126, 195,  22,  33,  78, 161],
        [124, 228, 116, 161,  88, 102],
        [  5,  43,  74, 132, 177, 204]], dtype=torch.int32)


In [69]:
c = torch.reshape(b, [1, 3, 3, 2])
c

tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)

In [70]:
print('如果张量在某个维度上只有一个元素,利用torch.squeeze可以消除这个维度,torch.unsqueeze正好相反')

如果张量在某个维度上只有一个元素,利用torch.squeeze可以消除这个维度,torch.unsqueeze正好相反


In [73]:
a = torch.tensor([[1.0, 2.0]])
print(a, a.shape)

tensor([[1., 2.]]) torch.Size([1, 2])


In [74]:
s = torch.squeeze(a)
print(s, s.shape)

tensor([1., 2.]) torch.Size([2])


In [75]:
print('在第0维插入长度为1的一个维度')
d = torch.unsqueeze(s, axis = 0)
print(d, d.shape)

在第0维插入长度为1的一个维度
tensor([[1., 2.]]) torch.Size([1, 2])


In [76]:
print('torch.transpose可以张量的维度,torch.transpose常用于图片存储格式的交换上')
print('如果是二维的矩阵,通常会调用矩阵的转置的方法matrix.t(), 等价于torch.transpose(matrix, 0, 1)')

torch.transpose可以张量的维度,torch.transpose常用于图片存储格式的交换上
如果是二维的矩阵,通常会调用矩阵的转置的方法matrix.t(), 等价于torch.transpose(matrix, 0, 1)


In [77]:
min, max = 0, 255
# Batch,Height, Width, Channel
data = torch.floor(min + (max - min) * torch.rand([100, 256, 256, 4])).int()
print(data.shape)

torch.Size([100, 256, 256, 4])


In [78]:
# 转换为Pytorch默认的图片的格式为：Batch, Channel, Height, Width
# 需要交换两次
data_t = torch.transpose(torch.transpose(data, 1, 2), 1, 3)
print(data_t.shape)

torch.Size([100, 4, 256, 256])


In [79]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [80]:
matrix.t()# 等价于torch.transpose(matrix, 0, 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

### 4. 合并分割

In [82]:
print('可以用torch.cat和torch.stack将多个张量合并,也可以利用torch.split()把一个张量分割成多个张量')
print('torch.cat是连接,不会增加维度, torch.stack是堆叠,会增加维度')

可以用torch.cat和torch.stack将多个张量合并,也可以利用torch.split()把一个张量分割成多个张量
torch.cat是连接,不会增加维度, torch.stack是堆叠,会增加维度


In [83]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
c = torch.tensor([[9.0, 10.0], [11.0, 12.0]])
a

tensor([[1., 2.],
        [3., 4.]])

In [85]:
abc_cat = torch.cat([a, b, c], dim = 0)
print(abc_cat, abc_cat.shape)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])


In [87]:
abc_stack = torch.stack([a, b, c], axis = 0) # torch中dim和axis参数名可以混用
print(abc_stack, abc_stack.shape)

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]]) torch.Size([3, 2, 2])


In [89]:
torch.cat([a, b, c], axis = 1)

tensor([[ 1.,  2.,  5.,  6.,  9., 10.],
        [ 3.,  4.,  7.,  8., 11., 12.]])

In [90]:
torch.stack([a, b, c], axis = 1)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])

In [91]:
print('torch.split是torch.cat的逆运算,可以指定分割份数平均分割,也可以通过指定每份的记录数量进行分割')
print(abc_cat)

torch.split是torch.cat的逆运算,可以指定分割份数平均分割,也可以通过指定每份的记录数量进行分割
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [92]:
a, b, c = torch.split(abc_cat, split_size_or_sections = 2, dim = 0) # 每份2个进行分割
a

tensor([[1., 2.],
        [3., 4.]])

In [93]:
b, c

(tensor([[5., 6.],
         [7., 8.]]),
 tensor([[ 9., 10.],
         [11., 12.]]))

In [94]:
abc_cat

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [99]:
p, q, r = torch.split(abc_cat, split_size_or_sections = [4, 1, 1], dim = 0) # 每份分别为[4, 1, 1]

In [100]:
p

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])

In [101]:
q

tensor([[ 9., 10.]])

In [102]:
r

tensor([[11., 12.]])