In [1]:
print('数学运算包括:标量运算,向量运算,矩阵运算,另外还有介绍运算的广播机制')

数学运算包括:标量运算,向量运算,矩阵运算,另外还有介绍运算的广播机制


### 1. 标量运算

In [3]:
import torch
import numpy as np

In [5]:
a = torch.tensor([[1.0, 2], [-3, 4.0]])
a

tensor([[ 1.,  2.],
        [-3.,  4.]])

In [6]:
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
b

tensor([[5., 6.],
        [7., 8.]])

In [7]:
a + b # 运算符重载

tensor([[ 6.,  8.],
        [ 4., 12.]])

In [8]:
a - b

tensor([[ -4.,  -4.],
        [-10.,  -4.]])

In [9]:
a * b # 对应元素相差

tensor([[  5.,  12.],
        [-21.,  32.]])

In [10]:
a @ b # 矩阵的乘法

tensor([[19., 22.],
        [13., 14.]])

In [11]:
a / b

tensor([[ 0.2000,  0.3333],
        [-0.4286,  0.5000]])

In [12]:
a ** 2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [13]:
a ** (0.5)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [14]:
a % 3 # 求模，也就是求余

tensor([[1., 2.],
        [-0., 1.]])

In [15]:
a // 3 # 	取整除 - 返回商的整数部分（向下取整）

D:\anconda3\lib\site-packages\torch\_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)


tensor([[ 0.,  0.],
        [-1.,  1.]])

In [16]:
a >= 2

tensor([[False,  True],
        [False,  True]])

In [18]:
torch.ge(a, 2) # ge:greater_equal缩写

tensor([[False,  True],
        [False,  True]])

In [19]:
(a >= 2) & (a <= 3)

tensor([[False,  True],
        [False, False]])

In [21]:
(a >= 2) | (a <= 3)

tensor([[True, True],
        [True, True]])

In [22]:
a == 5 # torch.eq(a, 5)

tensor([[False, False],
        [False, False]])

In [23]:
torch.sqrt(a)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [24]:
a = torch.tensor([1.0, 8.0])
b = torch.tensor([5.0, 6.0])
c = torch.tensor([6.0, 7.0])
a

tensor([1., 8.])

In [25]:
d = a + b + c
d

tensor([12., 21.])

In [26]:
torch.max(a, b)

tensor([5., 8.])

In [27]:
torch.min(a, b)

tensor([1., 6.])

In [28]:
x = torch.tensor([2.6, -2.7])
x

tensor([ 2.6000, -2.7000])

In [29]:
print('保留整数部分,四舍五入')
print(torch.round(x))

保留整数部分,四舍五入
tensor([ 3., -3.])


In [30]:
print('保留整数部分,向下归整')
print(torch.floor(x))

保留整数部分,向下归整
tensor([ 2., -3.])


In [31]:
print('保留整数部分,向上归整')
print(torch.ceil(x))

保留整数部分,向上归整
tensor([ 3., -2.])


In [32]:
print('保留整数部分,向0归整')
print(torch.trunc(x))

保留整数部分,向0归整
tensor([ 2., -2.])


In [33]:
x = torch.tensor([2.6, -2.7])
print('作除法取余数')
print(torch.fmod(x, 2))

作除法取余数
tensor([ 0.6000, -0.7000])


In [34]:
print('作除法取剩余的部分,结果恒正')
print(torch.remainder(x, 2))

作除法取剩余的部分,结果恒正
tensor([0.6000, 1.3000])


In [35]:
print('幅值裁剪')
x = torch.tensor([0.9, -0.8, 100.0, -20.0, 0.7])
x

幅值裁剪


tensor([  0.9000,  -0.8000, 100.0000, -20.0000,   0.7000])

In [37]:
y = torch.clamp(x, min = -1, max = 1)
y

tensor([ 0.9000, -0.8000,  1.0000, -1.0000,  0.7000])

In [38]:
z = torch.clamp(x, max = 1)
z

tensor([  0.9000,  -0.8000,   1.0000, -20.0000,   0.7000])

### 2. 向量运算

In [40]:
print('向量运算符只在一个特定轴上运算,将一个运算映射到一个标量或者另一个向量.')

向量运算符只在一个特定轴上运算,将一个运算映射到一个标量或者另一个向量.


In [41]:
a = torch.arange(1, 10).float()
a

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [42]:
print('求和')
print(torch.sum(a))

求和
tensor(45.)


In [43]:
print('求平均值')
print(torch.mean(a))

求平均值
tensor(5.)


In [44]:
print('最大值为:{}'.format(torch.max(a)))
print('最小值为:{}'.format(torch.min(a)))
print('累乘的结果为:{}'.format(torch.prod(a)))
print('标准差的值为:{}'.format(torch.std(a)))
print('方差的值为:{}'.format(torch.var(a)))
print('中位数为:{}'.format(torch.median(a)))

最大值为:9.0
最小值为:1.0
累乘的结果为:362880.0
标准差的值为:2.7386128902435303
方差的值为:7.5
中位数为:5.0


In [48]:
b = a.reshape(-1, 3)
print(b ,b.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])


In [49]:
print('每一列的最大值为:{}'.format(torch.max(b ,dim = 0)))

每一列的最大值为:torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))


In [50]:
print('每一行的最大值为:{}'.format(torch.max(b ,dim = 1)))

每一行的最大值为:torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [51]:
a = torch.arange(1, 10)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
# a[1] = a[0] + a[1]
# a[2] = a[1] + a[2]
torch.cumsum(a, 0)

tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [55]:
# a[1] = a[0] * a[1]
# a[2] = a[1] * a[2]
torch.cumprod(a, 0)

tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])

In [56]:
torch.cummax(a, 0)

torch.return_types.cummax(
values=tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]))

In [57]:
torch.cummax(a, 0).values

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
# 意思就是这个：y=[max(x1),max(x1,x2),max(x1,x2,x3),⋯]
torch.cummax(a, 0).indices

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
torch.cummin(a, 0)

torch.return_types.cummin(
values=tensor([1, 1, 1, 1, 1, 1, 1, 1, 1]),
indices=tensor([0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [62]:
test = torch.tensor([9, 10, 2, 3])
test

tensor([ 9, 10,  2,  3])

In [63]:
torch.cummax(test, dim = 0).values

tensor([ 9, 10, 10, 10])

In [72]:
a = torch.tensor([[9, 7, 8], [6, 5, 4], [3, 2, 10]]).float()
a

tensor([[ 9.,  7.,  8.],
        [ 6.,  5.,  4.],
        [ 3.,  2., 10.]])

In [73]:
torch.topk(a, 2, dim = 0).values # dim = 0 列

tensor([[ 9.,  7., 10.],
        [ 6.,  5.,  8.]])

In [74]:

torch.topk(a, 2, dim = 1).values

tensor([[ 9.,  8.],
        [ 6.,  5.],
        [10.,  3.]])

In [76]:
torch.sort(a,dim = 1).values

tensor([[ 7.,  8.,  9.],
        [ 4.,  5.,  6.],
        [ 2.,  3., 10.]])

In [79]:
torch.sort(a,dim = 0).values

tensor([[ 3.,  2.,  4.],
        [ 6.,  5.,  8.],
        [ 9.,  7., 10.]])

### 3. 矩阵运算

In [81]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[2, 0], [0, 2]])
a

tensor([[1, 2],
        [3, 4]])

In [83]:
print('矩阵的乘法')
print('第一种写法:{}'.format(a @ b))
print('第二种写法:{}'.format(torch.matmul(a, b)))
print('第三种写法:{}'.format(torch.mm(a, b)))

矩阵的乘法
第一种写法:tensor([[2, 4],
        [6, 8]])
第二种写法:tensor([[2, 4],
        [6, 8]])
第三种写法:tensor([[2, 4],
        [6, 8]])


In [85]:
a = torch.tensor([[1.0, 2], [3, 4]])
print('a的转置为:\n{}'.format(a.t()))

a的转置为:
tensor([[1., 3.],
        [2., 4.]])


In [86]:
a = torch.tensor([[1.0, 2], [3, 4]])
print('a的矩阵的逆,必须为浮点类型:\n{}'.format(torch.inverse(a)))

a的逆矩阵,必须为浮点类型:
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [88]:
a = torch.tensor([[1.0, 2], [3, 4]])
print('矩阵的trace:\n{}'.format(torch.trace(a)))

矩阵的trace:
5.0


In [89]:
a = torch.tensor([[1.0, 2], [3, 4]])
print('矩阵的范数:\n{}'.format(torch.norm(a)))

矩阵的范数:
5.4772257804870605


In [90]:
a = torch.tensor([[1.0, 2], [3, 4]])
print('矩阵a的行列式:{}'.format(torch.det(a)))

矩阵a的行列式:-1.9999998807907104


In [91]:
a = torch.tensor([[1.0, 2], [-5, 4]], dtype = torch.float)
print('矩阵的特征值和特别向量为:\n{}'.format(torch.eig(a, eigenvectors = True)))

矩阵的特征值和特别向量为:
torch.return_types.eig(
eigenvalues=tensor([[ 2.5000,  2.7839],
        [ 2.5000, -2.7839]]),
eigenvectors=tensor([[ 0.2535, -0.4706],
        [ 0.8452,  0.0000]]))


C:\Users\lzf\AppData\Local\Temp/ipykernel_11508/2861479895.py:2: UserWarning: torch.eig is deprecated in favor of torch.linalg.eig and will be removed in a future PyTorch release.
torch.linalg.eig returns complex tensors of dtype cfloat or cdouble rather than real tensors mimicking complex tensors.
L, _ = torch.eig(A)
should be replaced with
L_complex = torch.linalg.eigvals(A)
and
L, V = torch.eig(A, eigenvectors=True)
should be replaced with
L_complex, V_complex = torch.linalg.eig(A) (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:2897.)
  print('矩阵的特征值和特别向量为:\n{}'.format(torch.eig(a, eigenvectors = True)))


In [92]:
# 将矩阵QR分解，将一个矩阵分解为一个正交矩阵q和上三角矩阵r
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
q, r = torch.qr(a)

C:\Users\lzf\AppData\Local\Temp/ipykernel_11508/3438174488.py:3: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  ..\aten\src\ATen\native\BatchLinearAlgebra.cpp:1940.)
  q, r = torch.qr(a)


In [93]:
q

tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]])

In [94]:
r

tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]])

In [95]:
q @ r

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])

In [96]:
# 矩阵SVD分解
a = torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
u,s,v = torch.svd(a)

In [97]:
print('u:\n', u)
print('s:\n', s)
print('v:\n', v)

u:
 tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]])
s:
 tensor([9.5255, 0.5143])
v:
 tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]])


In [98]:
print('利用svd分解可以在Pytorch中实现主成分分析降维')
print(u @ torch.diag(s) @ v.t())

利用svd分解可以在Pytorch中实现主成分分析降维
tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


### 4. 广播机制

In [100]:
print('1. 如果张量的维度不一样,将维度小的扩展,直到两个张量维度一样')
print('2. 若两个张量在某个维度的长度是相同的,或其中一个张量在该维度的长度为1,就说这两个张量在该维度上是相容的')
print('3. 若两个张量在所有的维度是相容的，就可以使用广播')
print('4. 广播之后,每个维度的长度将取两个张量在该维度长度的较大值')
print('5. 在任何一个维度,如一个张量的长度为1,另一个张量的长度大于1,那么在该维度上,就好像是对第一个张量进行复制')

1. 如果张量的维度不一样,将维度小的扩展,直到两个张量维度一样
2. 若两个张量在某个维度的长度是相同的,或其中一个张量在该维度的长度为1,就说这两个张量在该维度上是相容的
3. 若两个张量在所有的维度是相容的，就可以使用广播
4. 广播之后,每个维度的长度将取两个张量在该维度长度的较大值
5. 在任何一个维度,如一个张量的长度为1,另一个张量的长度大于1,那么在该维度上,就好像是对第一个张量进行复制


In [101]:
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [102]:
b = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
b

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [103]:
a + b

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [104]:
a

tensor([1, 2, 3])

In [105]:
a_board, b_board = torch.broadcast_tensors(a, b)

In [106]:
b_board

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]])

In [107]:
a_board

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [108]:
a_board + b_board

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])